### ISSUE TITLE
无法登陆启用了外置登录在线验证的服务器

### ISSUE THREAD

**Issue by PDUMC** [root-S7/HMCL-PE-CN#2]
提示无效会话

**Comment by root-S7** [comment]
外置登录用的是皮肤站还是统一登录呢?
如果是皮肤站提供链接和账户信息（可qq私信发送
如果是统一登录则提供32位服务器ID和不能登录的账户

qq3020825808

**Comment by root-S7** [comment]
好了，我知道啥问题了：当你的皮肤站账户内有多个用户名时将无法登录。等我考完试在修复它

**Comment by root-S7** [comment]
https://github.com/root-S7/HMCL-PE-CN/commit/2428b7d809ec228d4d6fe028c4d1e82ac4db2d22
